version: '3.4'

services:
  administrativo:
    image: ${DOCKER_REGISTRY-}administrativo
    build:
      context: .\Administrativo
      dockerfile: Dockerfile

  site:
    image: ${DOCKER_REGISTRY-}site
    build:
      context: .\Site
      dockerfile: Dockerfile


  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .\API
      dockerfile: Dockerfile

