version: '3.4'

services:
  site:
    ports:
      - "80"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
        
  api:
    ports:
      - "80"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3

  administrativo:
    ports:
      - "80"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4

  db:
    image: microsoft/mssql-server-windows-express
    environment:
      sa_password: "123Express123"
      accept_eula: "y"
      MSSQL_PID: "Express"
      MSSQL_DB: "CompanyNameProducao"
    ports:
      - "1433" # for debug. Remove this for production
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5

  redis:
    image: redis
    ports:
      - "16379:6379"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
networks:
  vpcbr:
    driver: nat
    ipam:
     config:
       - subnet: 10.5.0.0/16


