//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acontecimentos
    {
        public Acontecimentos()
        {
            this.FotosAcontecimentoes = new HashSet<FotosAcontecimentoes>();
        }
    
        public int Id { get; set; }
        public string Local { get; set; }
        public System.DateTime Data { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public string HoraInicio { get; set; }
        public string HoraFim { get; set; }
        public int EventoId { get; set; }
        public string FlickrId { get; set; }
        public bool Excluido { get; set; }
        public bool Liberado { get; set; }
    
        public virtual Eventos Eventos { get; set; }
        public virtual ICollection<FotosAcontecimentoes> FotosAcontecimentoes { get; set; }
    }
}
