//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApoioPADs
    {
        public ApoioPADs()
        {
            this.EGolPADs = new HashSet<EGolPADs>();
            this.NoticiasPADs = new HashSet<NoticiasPADs>();
            this.RedesSociaisPADs = new HashSet<RedesSociaisPADs>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Logo { get; set; }
        public bool Excluido { get; set; }
        public System.DateTime DataCadastro { get; set; }
    
        public virtual ICollection<EGolPADs> EGolPADs { get; set; }
        public virtual ICollection<NoticiasPADs> NoticiasPADs { get; set; }
        public virtual ICollection<RedesSociaisPADs> RedesSociaisPADs { get; set; }
    }
}
