//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apresentadores
    {
        public Apresentadores()
        {
            this.Programacao = new HashSet<Programacao>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public string fotoInterna { get; set; }
        public string fotoExterna { get; set; }
        public string chamada { get; set; }
        public string texto { get; set; }
        public string chave { get; set; }
        public bool excluido { get; set; }
        public string Instagram { get; set; }
        public string twitter { get; set; }
        public Nullable<bool> participanteConvidado { get; set; }
        public string facebook { get; set; }
        public System.DateTime DataCadastro { get; set; }
    
        public virtual ICollection<Programacao> Programacao { get; set; }
    }
}
