//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreasADM
    {
        public AreasADM()
        {
            this.Logs = new HashSet<Logs>();
        }
    
        public int Id { get; set; }
        public string Area { get; set; }
    
        public virtual ICollection<Logs> Logs { get; set; }
    }
}
