//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssuntoMateria
    {
        public AssuntoMateria()
        {
            this.Materia = new HashSet<Materia>();
        }
    
        public int id { get; set; }
        public string assunto { get; set; }
    
        public virtual ICollection<Materia> Materia { get; set; }
    }
}
