//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audios
    {
        public int Id { get; set; }
        public string Legenda { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public Nullable<int> ColecaoId { get; set; }
        public Nullable<bool> Excluido { get; set; }
        public Nullable<bool> Liberado { get; set; }
        public string Url { get; set; }
    
        public virtual ColecoesAudios ColecoesAudios { get; set; }
    }
}
