//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BannersVisualizacoesCliques
    {
        public int Id { get; set; }
        public int CodigoBanner { get; set; }
        public bool Visualizacao { get; set; }
        public bool Clique { get; set; }
        public System.DateTime DataCadastro { get; set; }
    
        public virtual Banners Banners { get; set; }
    }
}
