//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banners
    {
        public Banners()
        {
            this.AreaBanner = new HashSet<AreaBanner>();
            this.BannersVisualizacoesCliques = new HashSet<BannersVisualizacoesCliques>();
        }
    
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Arquivo { get; set; }
        public string Anunciante { get; set; }
        public string Link { get; set; }
        public bool TipoArquivo { get; set; }
        public Nullable<int> Exibicoes { get; set; }
        public Nullable<int> Cliques { get; set; }
        public bool Excluido { get; set; }
        public bool Liberado { get; set; }
        public System.DateTime DataInicio { get; set; }
        public System.DateTime DataFim { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public Nullable<int> Local { get; set; }
        public string Arquivo2 { get; set; }
        public string Html { get; set; }
    
        public virtual ICollection<AreaBanner> AreaBanner { get; set; }
        public virtual ICollection<BannersVisualizacoesCliques> BannersVisualizacoesCliques { get; set; }
    }
}
