//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BastidoresMidias
    {
        public int id { get; set; }
        public Nullable<int> idGaleria { get; set; }
        public string midia { get; set; }
        public string legenda { get; set; }
        public bool video { get; set; }
        public bool ativo { get; set; }
        public bool excluido { get; set; }
        public System.DateTime dataCadastro { get; set; }
    
        public virtual Bastidores Bastidores { get; set; }
    }
}
