//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bastidores
    {
        public Bastidores()
        {
            this.BastidoresMidias = new HashSet<BastidoresMidias>();
        }
    
        public int id { get; set; }
        public string titulo { get; set; }
        public string chamada { get; set; }
        public string texto { get; set; }
        public string chave { get; set; }
        public bool excluido { get; set; }
        public System.DateTime dataCadastro { get; set; }
        public bool ativo { get; set; }
    
        public virtual ICollection<BastidoresMidias> BastidoresMidias { get; set; }
    }
}
