//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriasAudios
    {
        public CategoriasAudios()
        {
            this.ColecoesAudios = new HashSet<ColecoesAudios>();
        }
    
        public int Id { get; set; }
        public string Descricao { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public bool Excluido { get; set; }
        public bool Liberado { get; set; }
    
        public virtual ICollection<ColecoesAudios> ColecoesAudios { get; set; }
    }
}
