//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cidade
    {
        public cidade()
        {
            this.Ouvintes = new HashSet<Ouvintes>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual ICollection<Ouvintes> Ouvintes { get; set; }
    }
}
