//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColecoesAudios
    {
        public ColecoesAudios()
        {
            this.Audios = new HashSet<Audios>();
        }
    
        public int Id { get; set; }
        public string Titulo { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public bool Excluido { get; set; }
        public bool Liberado { get; set; }
        public Nullable<int> CategoriaId { get; set; }
    
        public virtual ICollection<Audios> Audios { get; set; }
        public virtual CategoriasAudios CategoriasAudios { get; set; }
    }
}
