//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colunista
    {
        public Colunista()
        {
            this.ColunistaSeguidores = new HashSet<ColunistaSeguidores>();
            this.Noticias = new HashSet<Noticias>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public string descricao { get; set; }
        public string foto { get; set; }
        public string fotoMini { get; set; }
        public string chave { get; set; }
        public bool liberado { get; set; }
        public bool excluido { get; set; }
        public System.DateTime dataCadastro { get; set; }
        public string sexo { get; set; }
        public int Ordem { get; set; }
    
        public virtual ICollection<ColunistaSeguidores> ColunistaSeguidores { get; set; }
        public virtual ICollection<Noticias> Noticias { get; set; }
    }
}
