//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentarios
    {
        public Comentarios()
        {
            this.Comentarios1 = new HashSet<Comentarios>();
        }
    
        public int Id { get; set; }
        public string Texto { get; set; }
        public string CPF { get; set; }
        public string Nome { get; set; }
        public Nullable<int> IdComentarioRaiz { get; set; }
        public int IdNoticia { get; set; }
        public bool Bloqueado { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public string IPAcesso { get; set; }
        public int Gostei { get; set; }
        public int NaoGostei { get; set; }
        public string UrlFacebook { get; set; }
    
        public virtual ICollection<Comentarios> Comentarios1 { get; set; }
        public virtual Comentarios Comentarios2 { get; set; }
        public virtual Noticias Noticias { get; set; }
    }
}
