//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Editoriais
    {
        public Editoriais()
        {
            this.Categorias = new HashSet<Categorias>();
            this.Editoriais_Equipe = new HashSet<Editoriais_Equipe>();
            this.Programacao = new HashSet<Programacao>();
            this.Galeria = new HashSet<Galeria>();
            this.Noticias = new HashSet<Noticias>();
            this.Especiais_Secoes = new HashSet<Especiais_Secoes>();
            this.Times = new HashSet<Times>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public bool especial { get; set; }
        public Nullable<int> modeloEspecial { get; set; }
        public bool ativo { get; set; }
        public bool excluido { get; set; }
        public string chave { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public bool esportes { get; set; }
        public string Action { get; set; }
        public bool canal { get; set; }
        public string Descricao { get; set; }
        public string FotoCapa { get; set; }
    
        public virtual ICollection<Categorias> Categorias { get; set; }
        public virtual ICollection<Editoriais_Equipe> Editoriais_Equipe { get; set; }
        public virtual ICollection<Programacao> Programacao { get; set; }
        public virtual ICollection<Galeria> Galeria { get; set; }
        public virtual ICollection<Noticias> Noticias { get; set; }
        public virtual Especiais_Modelos Especiais_Modelos { get; set; }
        public virtual ICollection<Especiais_Secoes> Especiais_Secoes { get; set; }
        public virtual ICollection<Times> Times { get; set; }
    }
}
