//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Editoriais_Equipe
    {
        public int id { get; set; }
        public Nullable<int> EditoriaisId { get; set; }
        public string nome { get; set; }
        public string texto { get; set; }
        public string funcao { get; set; }
        public string imagem { get; set; }
        public string imagemVertical { get; set; }
        public string instagram { get; set; }
        public string facebook { get; set; }
        public string twitter { get; set; }
        public bool excluido { get; set; }
        public string chave { get; set; }
        public System.DateTime DataCadastro { get; set; }
    
        public virtual Editoriais Editoriais { get; set; }
    }
}
