//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EGolPADs
    {
        public int Id { get; set; }
        public string Placar { get; set; }
        public Nullable<int> ApoioId { get; set; }
        public int MandanteId { get; set; }
        public int VisitanteId { get; set; }
        public bool Excluido { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public string Jogador { get; set; }
        public string HoraDoGol { get; set; }
        public string BgColor { get; set; }
        public bool GolMandante { get; set; }
        public string HashTag { get; set; }
    
        public virtual ApoioPADs ApoioPADs { get; set; }
        public virtual TimesPADs TimesPADs { get; set; }
        public virtual TimesPADs TimesPADs1 { get; set; }
    }
}
