//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elencos
    {
        public int Id { get; set; }
        public int TimeId { get; set; }
        public string Nome { get; set; }
        public string Posicao { get; set; }
        public bool Ativo { get; set; }
        public bool Excluido { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public string Foto { get; set; }
    
        public virtual Times Times { get; set; }
    }
}
