//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enquete
    {
        public Enquete()
        {
            this.Respostas = new HashSet<Respostas>();
        }
    
        public int id { get; set; }
        public string pergunta { get; set; }
        public bool ativa { get; set; }
        public bool excluido { get; set; }
        public bool destaque { get; set; }
        public string chave { get; set; }
        public System.DateTime dataCadastro { get; set; }
        public Nullable<System.DateTime> dataInicioVotacao { get; set; }
        public Nullable<System.DateTime> dataFimVotacao { get; set; }
        public Nullable<System.DateTime> dataFimResultado { get; set; }
    
        public virtual ICollection<Respostas> Respostas { get; set; }
    }
}
