//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Especiais_Modelos
    {
        public Especiais_Modelos()
        {
            this.Editoriais = new HashSet<Editoriais>();
        }
    
        public int Id { get; set; }
        public string Tipo { get; set; }
        public bool TemSecao { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public string Action { get; set; }
        public bool especial { get; set; }
    
        public virtual ICollection<Editoriais> Editoriais { get; set; }
    }
}
