//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eventos
    {
        public Eventos()
        {
            this.Acontecimentos = new HashSet<Acontecimentos>();
        }
    
        public int Id { get; set; }
        public string Titulo { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public bool Liberado { get; set; }
        public string Texto { get; set; }
        public string Imagem { get; set; }
        public bool Excluido { get; set; }
    
        public virtual ICollection<Acontecimentos> Acontecimentos { get; set; }
    }
}
