//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaleConosco
    {
        public int id { get; set; }
        public string assunto { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public string estado { get; set; }
        public string cidade { get; set; }
        public string celular { get; set; }
        public string telefone { get; set; }
        public string mensagem { get; set; }
        public System.DateTime dataCadastro { get; set; }
        public string resposta { get; set; }
        public Nullable<System.DateTime> dataResposta { get; set; }
        public bool excluido { get; set; }
        public byte lida { get; set; }
    }
}
