//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Galeria
    {
        public Galeria()
        {
            this.Midias = new HashSet<Midias>();
            this.Editoriais = new HashSet<Editoriais>();
            this.Noticias = new HashSet<Noticias>();
        }
    
        public int id { get; set; }
        public string titulo { get; set; }
        public string chamada { get; set; }
        public string texto { get; set; }
        public bool Fixa { get; set; }
        public string chave { get; set; }
        public bool excluido { get; set; }
        public System.DateTime dataCadastro { get; set; }
        public bool ativo { get; set; }
    
        public virtual ICollection<Midias> Midias { get; set; }
        public virtual ICollection<Editoriais> Editoriais { get; set; }
        public virtual ICollection<Noticias> Noticias { get; set; }
    }
}
