//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario_programacao
    {
        public int id { get; set; }
        public Nullable<int> idPrograma { get; set; }
        public Nullable<int> diaSemana { get; set; }
        public string horario { get; set; }
    
        public virtual Programacao Programacao { get; set; }
    }
}
