//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LiveStreamings
    {
        public int Id { get; set; }
        public string Legenda { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public Nullable<System.DateTime> DataFinalizacao { get; set; }
        public bool Excluido { get; set; }
        public bool Ativo { get; set; }
        public int IdNoticia { get; set; }
        public string CodigoTransmissao { get; set; }
    
        public virtual Noticias Noticias { get; set; }
    }
}
