//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int AreaId { get; set; }
        public int Acao { get; set; }
        public string IP { get; set; }
        public Nullable<int> Detalhes { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual AreasADM AreasADM { get; set; }
    }
}
