//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materia
    {
        public Materia()
        {
            this.MateriaNovidades = new HashSet<MateriaNovidades>();
        }
    
        public int id { get; set; }
        public int idProgramacao { get; set; }
        public int idAssunto { get; set; }
        public string titulo { get; set; }
        public string chamada { get; set; }
        public string texto { get; set; }
        public string foto { get; set; }
        public int status { get; set; }
        public string chave { get; set; }
        public bool excluido { get; set; }
        public System.DateTime dataCadastro { get; set; }
    
        public virtual AssuntoMateria AssuntoMateria { get; set; }
        public virtual ICollection<MateriaNovidades> MateriaNovidades { get; set; }
        public virtual Programacao Programacao { get; set; }
    }
}
