//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MateriaNovidades
    {
        public int id { get; set; }
        public int idMateria { get; set; }
        public string status { get; set; }
        public System.DateTime dataPrograma { get; set; }
        public string novidades { get; set; }
        public string audio { get; set; }
        public System.DateTime dataCadastro { get; set; }
        public bool excluido { get; set; }
    
        public virtual Materia Materia { get; set; }
    }
}
