//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RadioCompanyNameContext : DbContext
    {
        public RadioCompanyNameContext()
            : base("name=RadioCompanyNameContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AssuntoMateria> AssuntoMateria { get; set; }
        public DbSet<Categorias> Categorias { get; set; }
        public DbSet<CategoriasMapa> CategoriasMapa { get; set; }
        public DbSet<cidade> cidade { get; set; }
        public DbSet<Editoriais_Equipe> Editoriais_Equipe { get; set; }
        public DbSet<Enquete> Enquete { get; set; }
        public DbSet<FaleConosco> FaleConosco { get; set; }
        public DbSet<Galeria> Galeria { get; set; }
        public DbSet<Horario_programacao> Horario_programacao { get; set; }
        public DbSet<Materia> Materia { get; set; }
        public DbSet<MateriaNovidades> MateriaNovidades { get; set; }
        public DbSet<Midias> Midias { get; set; }
        public DbSet<Newsletter> Newsletter { get; set; }
        public DbSet<NoticiasRegioes> NoticiasRegioes { get; set; }
        public DbSet<Respostas> Respostas { get; set; }
        public DbSet<RotasNoRio> RotasNoRio { get; set; }
        public DbSet<Tags> Tags { get; set; }
        public DbSet<TrabalheConosco> TrabalheConosco { get; set; }
        public DbSet<Transporte> Transporte { get; set; }
        public DbSet<Equipe> Equipe { get; set; }
        public DbSet<Bastidores> Bastidores { get; set; }
        public DbSet<BastidoresMidias> BastidoresMidias { get; set; }
        public DbSet<Apresentadores> Apresentadores { get; set; }
        public DbSet<Programacao> Programacao { get; set; }
        public DbSet<MidiaKit> MidiaKit { get; set; }
        public DbSet<AreaBanner> AreaBanner { get; set; }
        public DbSet<Banners> Banners { get; set; }
        public DbSet<BannersVisualizacoesCliques> BannersVisualizacoesCliques { get; set; }
        public DbSet<Colunista> Colunista { get; set; }
        public DbSet<ColunistaSeguidores> ColunistaSeguidores { get; set; }
        public DbSet<Especiais> Especiais { get; set; }
        public DbSet<OuvintesArquivos> OuvintesArquivos { get; set; }
        public DbSet<Regioes> Regioes { get; set; }
        public DbSet<estado> estado { get; set; }
        public DbSet<Promocoes> Promocoes { get; set; }
        public DbSet<Promocoes_Participantes> Promocoes_Participantes { get; set; }
        public DbSet<Promocoes_Resultados> Promocoes_Resultados { get; set; }
        public DbSet<Editoriais> Editoriais { get; set; }
        public DbSet<Noticias> Noticias { get; set; }
        public DbSet<Especiais_Modelos> Especiais_Modelos { get; set; }
        public DbSet<Especiais_Secoes> Especiais_Secoes { get; set; }
        public DbSet<Secoes_Locais> Secoes_Locais { get; set; }
        public DbSet<Blocos> Blocos { get; set; }
        public DbSet<Elencos> Elencos { get; set; }
        public DbSet<Times> Times { get; set; }
        public DbSet<Acontecimentos> Acontecimentos { get; set; }
        public DbSet<Eventos> Eventos { get; set; }
        public DbSet<AreasADM> AreasADM { get; set; }
        public DbSet<Logs> Logs { get; set; }
        public DbSet<Horoscopoes> Horoscopoes { get; set; }
        public DbSet<Bairros> Bairros { get; set; }
        public DbSet<FotosAcontecimentoes> FotosAcontecimentoes { get; set; }
        public DbSet<Radios> Radios { get; set; }
        public DbSet<Audios> Audios { get; set; }
        public DbSet<CategoriasAudios> CategoriasAudios { get; set; }
        public DbSet<ColecoesAudios> ColecoesAudios { get; set; }
        public DbSet<Ouvintes> Ouvintes { get; set; }
        public DbSet<Comentarios> Comentarios { get; set; }
        public DbSet<LiveStreamings> LiveStreamings { get; set; }
        public DbSet<GruposPush> GruposPush { get; set; }
        public DbSet<NotificacoesPush> NotificacoesPush { get; set; }
        public DbSet<RedesSociais> RedesSociais { get; set; }
        public DbSet<ApoioPADs> ApoioPADs { get; set; }
        public DbSet<EGolPADs> EGolPADs { get; set; }
        public DbSet<NoticiasPADs> NoticiasPADs { get; set; }
        public DbSet<RedesSociaisPADs> RedesSociaisPADs { get; set; }
        public DbSet<TimesPADs> TimesPADs { get; set; }
    }
}
