//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noticias
    {
        public Noticias()
        {
            this.Categorias = new HashSet<Categorias>();
            this.Editoriais = new HashSet<Editoriais>();
            this.Tags = new HashSet<Tags>();
            this.Comentarios = new HashSet<Comentarios>();
            this.LiveStreamings = new HashSet<LiveStreamings>();
            this.NotificacoesPush = new HashSet<NotificacoesPush>();
        }
    
        public int id { get; set; }
        public Nullable<int> idColunista { get; set; }
        public string audio { get; set; }
        public Nullable<int> CategoriaMapaId { get; set; }
        public string titulo { get; set; }
        public string subtitulo { get; set; }
        public string texto { get; set; }
        public string foto { get; set; }
        public string fotoDescricao { get; set; }
        public string fotoMini { get; set; }
        public string link { get; set; }
        public bool destaque { get; set; }
        public bool destaqueHome { get; set; }
        public bool DestaqueHomeMenor { get; set; }
        public bool assuntoSemana { get; set; }
        public string chamada { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public Nullable<int> idGaleria { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public string videoYoutube { get; set; }
        public bool videoDestaqueHome { get; set; }
        public bool transito { get; set; }
        public Nullable<int> RegiaoId { get; set; }
        public System.DateTime dataAtualizacao { get; set; }
        public string url { get; set; }
        public bool plantao { get; set; }
        public int visualizacao { get; set; }
        public bool projeto { get; set; }
        public bool liberado { get; set; }
        public string fotoCredito { get; set; }
        public string porAutor { get; set; }
        public bool excluido { get; set; }
        public System.DateTime dataCadastro { get; set; }
        public bool destaqueEditoria { get; set; }
        public string local { get; set; }
        public Nullable<bool> migrado { get; set; }
        public Nullable<int> idMigrado { get; set; }
        public Nullable<int> TipoDestaque { get; set; }
        public bool ExibirImagemInterna { get; set; }
        public string TituloCapa { get; set; }
        public bool CreditoFotoNoTexto { get; set; }
    
        public virtual CategoriasMapa CategoriasMapa { get; set; }
        public virtual Colunista Colunista { get; set; }
        public virtual Galeria Galeria { get; set; }
        public virtual NoticiasRegioes NoticiasRegioes { get; set; }
        public virtual ICollection<Categorias> Categorias { get; set; }
        public virtual ICollection<Editoriais> Editoriais { get; set; }
        public virtual ICollection<Tags> Tags { get; set; }
        public virtual ICollection<Comentarios> Comentarios { get; set; }
        public virtual ICollection<LiveStreamings> LiveStreamings { get; set; }
        public virtual ICollection<NotificacoesPush> NotificacoesPush { get; set; }
    }
}
