//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificacoesPush
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public Nullable<int> idGrupo { get; set; }
        public Nullable<int> idNoticia { get; set; }
        public Nullable<int> GrupoPush_Id { get; set; }
        public Nullable<int> Noticia_id { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public bool Enviado { get; set; }
        public string RetornoAPI { get; set; }
    
        public virtual GruposPush GruposPush { get; set; }
        public virtual Noticias Noticias { get; set; }
    }
}
