//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OuvintesArquivos
    {
        public int id { get; set; }
        public int idOuvinteDenuncia { get; set; }
        public string Arquivo { get; set; }
        public System.DateTime DataCadastro { get; set; }
    
        public virtual Ouvintes Ouvintes { get; set; }
    }
}
