//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ouvintes
    {
        public Ouvintes()
        {
            this.OuvintesArquivos = new HashSet<OuvintesArquivos>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public string telefone { get; set; }
        public Nullable<int> cidade_id { get; set; }
        public Nullable<int> regiaoId { get; set; }
        public string bairro { get; set; }
        public string endereco { get; set; }
        public string assunto { get; set; }
        public string horario { get; set; }
        public System.DateTime data { get; set; }
        public string comentario { get; set; }
        public bool liberado { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public bool excluido { get; set; }
    
        public virtual cidade cidade { get; set; }
        public virtual Regioes Regioes { get; set; }
        public virtual ICollection<OuvintesArquivos> OuvintesArquivos { get; set; }
    }
}
