//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programacao
    {
        public Programacao()
        {
            this.Horario_programacao = new HashSet<Horario_programacao>();
            this.Materia = new HashSet<Materia>();
            this.Apresentadores = new HashSet<Apresentadores>();
        }
    
        public int id { get; set; }
        public int editoriaId { get; set; }
        public string nome { get; set; }
        public string logo { get; set; }
        public string imagem { get; set; }
        public int periodo { get; set; }
        public string texto { get; set; }
        public string chamada { get; set; }
        public Nullable<int> diaSemana { get; set; }
        public Nullable<System.TimeSpan> horario { get; set; }
        public Nullable<System.DateTime> dataCadastro { get; set; }
        public bool excluido { get; set; }
        public string chave { get; set; }
    
        public virtual ICollection<Horario_programacao> Horario_programacao { get; set; }
        public virtual ICollection<Materia> Materia { get; set; }
        public virtual ICollection<Apresentadores> Apresentadores { get; set; }
        public virtual Editoriais Editoriais { get; set; }
    }
}
