//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promocoes_Participantes
    {
        public int Id { get; set; }
        public int PromocaoCodigo { get; set; }
        public int ParticipanteCodigo { get; set; }
        public string CampoExtra { get; set; }
        public System.DateTime DataCadastro { get; set; }
    
        public virtual Promocoes Promocoes { get; set; }
    }
}
