//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promocoes
    {
        public Promocoes()
        {
            this.Promocoes_Participantes = new HashSet<Promocoes_Participantes>();
            this.Promocoes_Resultados = new HashSet<Promocoes_Resultados>();
        }
    
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public string Premio { get; set; }
        public int Quantidade { get; set; }
        public System.DateTime DataInicio { get; set; }
        public System.DateTime DataFim { get; set; }
        public string Imagem { get; set; }
        public string Regulamento { get; set; }
        public string EmailTexto { get; set; }
        public bool ResultadoAutomatico { get; set; }
        public int TipoPromocao { get; set; }
        public bool Ativo { get; set; }
        public bool Excluido { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
    
        public virtual ICollection<Promocoes_Participantes> Promocoes_Participantes { get; set; }
        public virtual ICollection<Promocoes_Resultados> Promocoes_Resultados { get; set; }
    }
}
