//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Radios
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Stream1 { get; set; }
        public string Stream2 { get; set; }
        public string Chave { get; set; }
        public bool Ativo { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public int TipoStream1 { get; set; }
        public int TipoStream2 { get; set; }
        public string Imagem { get; set; }
    }
}
