//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respostas
    {
        public int id { get; set; }
        public Nullable<int> idEnquete { get; set; }
        public string resposta { get; set; }
        public bool excluido { get; set; }
        public Nullable<bool> certa { get; set; }
        public int votos { get; set; }
    
        public virtual Enquete Enquete { get; set; }
    }
}
