//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Secoes_Locais
    {
        public int Id { get; set; }
        public int SecaoId { get; set; }
        public string Tipo { get; set; }
        public string Titulo { get; set; }
        public string Chave { get; set; }
        public string Imagem { get; set; }
        public string Descricao { get; set; }
        public string Endereco { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public bool Ativo { get; set; }
        public bool Excluido { get; set; }
        public System.DateTime DataCadastro { get; set; }
    
        public virtual Especiais_Secoes Especiais_Secoes { get; set; }
    }
}
