//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimesPADs
    {
        public TimesPADs()
        {
            this.EGolPADs = new HashSet<EGolPADs>();
            this.EGolPADs1 = new HashSet<EGolPADs>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Logo { get; set; }
        public bool Excluido { get; set; }
        public System.DateTime DataCadastro { get; set; }
    
        public virtual ICollection<EGolPADs> EGolPADs { get; set; }
        public virtual ICollection<EGolPADs> EGolPADs1 { get; set; }
    }
}
