//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Times
    {
        public Times()
        {
            this.Elencos = new HashSet<Elencos>();
        }
    
        public int Id { get; set; }
        public int EditoriaId { get; set; }
        public string Nome { get; set; }
        public string Chave { get; set; }
        public string Cor { get; set; }
        public bool Ativo { get; set; }
        public string Informacoes { get; set; }
        public string Titulos { get; set; }
        public bool Excluido { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public string Escudo { get; set; }
    
        public virtual Editoriais Editoriais { get; set; }
        public virtual ICollection<Elencos> Elencos { get; set; }
    }
}
