//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administrativo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrabalheConosco
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string celular { get; set; }
        public string telefone { get; set; }
        public int sexo { get; set; }
        public string estado { get; set; }
        public string cidade { get; set; }
        public string areaPretencao { get; set; }
        public System.DateTime dataNascimento { get; set; }
        public string curriculo { get; set; }
        public string email { get; set; }
        public System.DateTime dataCadastro { get; set; }
    }
}
